[theme]
primaryColor = "#10B981"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1F2C"
textColor = "#F3F4F6"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
